name: flutter_share
description: Simple way to share message, links or files from your flutter app for Android and IOS (Enter to see some gifs).
version: 2.0.0
homepage: https://github.com/lubritto/flutter_share

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.fluttershare
        pluginClass: FlutterSharePlugin
      ios:
        pluginClass: FlutterSharePlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
